//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SpecSvc.Pipeline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StepDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StepDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoServices.SpecSvc.Process.StepDescriptions", typeof(StepDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CalculateDescription {
            get {
                return ResourceManager.GetString("CalculateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string CalculateTitle {
            get {
                return ResourceManager.GetString("CalculateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CompositeDescription {
            get {
                return ResourceManager.GetString("CompositeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate composite.
        /// </summary>
        internal static string CompositeTitle {
            get {
                return ResourceManager.GetString("CompositeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinuumFitDescription {
            get {
                return ResourceManager.GetString("ContinuumFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit continuum.
        /// </summary>
        internal static string ContinuumFitTitle {
            get {
                return ResourceManager.GetString("ContinuumFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConvolutionDescription {
            get {
                return ResourceManager.GetString("ConvolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolve with Gaussian.
        /// </summary>
        internal static string ConvolutionTitle {
            get {
                return ResourceManager.GetString("ConvolutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DereddenDescription {
            get {
                return ResourceManager.GetString("DereddenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deredden.
        /// </summary>
        internal static string DereddenTitle {
            get {
                return ResourceManager.GetString("DereddenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FluxDescription {
            get {
                return ResourceManager.GetString("FluxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute synthetic flux.
        /// </summary>
        internal static string FluxTitle {
            get {
                return ResourceManager.GetString("FluxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates spectral indices (Lick/IDS, DTT, BH, D4000).
        /// </summary>
        internal static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral indices.
        /// </summary>
        internal static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LineFitDescription {
            get {
                return ResourceManager.GetString("LineFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit spectral lines.
        /// </summary>
        internal static string LineFitTitle {
            get {
                return ResourceManager.GetString("LineFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NormalizeDescription {
            get {
                return ResourceManager.GetString("NormalizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize spectrum.
        /// </summary>
        internal static string NormalizeTitle {
            get {
                return ResourceManager.GetString("NormalizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PcaDescription {
            get {
                return ResourceManager.GetString("PcaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine principal components.
        /// </summary>
        internal static string PcaTitle {
            get {
                return ResourceManager.GetString("PcaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RebinDescription {
            get {
                return ResourceManager.GetString("RebinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebin spectrum.
        /// </summary>
        internal static string RebinTitle {
            get {
                return ResourceManager.GetString("RebinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RedshiftDescription {
            get {
                return ResourceManager.GetString("RedshiftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change redshift frame.
        /// </summary>
        internal static string RedshiftTitle {
            get {
                return ResourceManager.GetString("RedshiftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this processing step is preceeded by multiple continuum fit steps it selects the one with the smallest Chi2 value..
        /// </summary>
        internal static string SelectBestFitDescription {
            get {
                return ResourceManager.GetString("SelectBestFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select best fit.
        /// </summary>
        internal static string SelectBestFitTitle {
            get {
                return ResourceManager.GetString("SelectBestFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WavelengthConversionDescription {
            get {
                return ResourceManager.GetString("WavelengthConversionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert wavelength.
        /// </summary>
        internal static string WavelengthConversionTitle {
            get {
                return ResourceManager.GetString("WavelengthConversionTitle", resourceCulture);
            }
        }
    }
}
