//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SpecSvc.Pipeline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StepDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StepDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.SpecSvc.Pipeline.StepDescriptions", typeof(StepDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ArithmeticDescription {
            get {
                return ResourceManager.GetString("ArithmeticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic.
        /// </summary>
        public static string ArithmeticTitle {
            get {
                return ResourceManager.GetString("ArithmeticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BinByDescription {
            get {
                return ResourceManager.GetString("BinByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin by parameter.
        /// </summary>
        public static string BinByTitle {
            get {
                return ResourceManager.GetString("BinByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompositeDescription {
            get {
                return ResourceManager.GetString("CompositeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite.
        /// </summary>
        public static string CompositeTitle {
            get {
                return ResourceManager.GetString("CompositeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContinuumFitDescription {
            get {
                return ResourceManager.GetString("ContinuumFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuum fit.
        /// </summary>
        public static string ContinuumFitTitle {
            get {
                return ResourceManager.GetString("ContinuumFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConvolutionDescription {
            get {
                return ResourceManager.GetString("ConvolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian convolution.
        /// </summary>
        public static string ConvolutionTitle {
            get {
                return ResourceManager.GetString("ConvolutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DereddenDescription {
            get {
                return ResourceManager.GetString("DereddenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deredden.
        /// </summary>
        public static string DereddenTitle {
            get {
                return ResourceManager.GetString("DereddenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FluxDescription {
            get {
                return ResourceManager.GetString("FluxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthetic flux.
        /// </summary>
        public static string FluxTitle {
            get {
                return ResourceManager.GetString("FluxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates spectral indices (Lick/IDS, DTT, BH, D4000).
        /// </summary>
        public static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lick index.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit emission lines.
        /// </summary>
        public static string LineFitDescription {
            get {
                return ResourceManager.GetString("LineFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line fit.
        /// </summary>
        public static string LineFitTitle {
            get {
                return ResourceManager.GetString("LineFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NormalizeDescription {
            get {
                return ResourceManager.GetString("NormalizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize.
        /// </summary>
        public static string NormalizeTitle {
            get {
                return ResourceManager.GetString("NormalizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PcaDescription {
            get {
                return ResourceManager.GetString("PcaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Components.
        /// </summary>
        public static string PcaTitle {
            get {
                return ResourceManager.GetString("PcaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RebinDescription {
            get {
                return ResourceManager.GetString("RebinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebin.
        /// </summary>
        public static string RebinTitle {
            get {
                return ResourceManager.GetString("RebinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RedshiftDescription {
            get {
                return ResourceManager.GetString("RedshiftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame conversion.
        /// </summary>
        public static string RedshiftTitle {
            get {
                return ResourceManager.GetString("RedshiftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this processing step is preceeded by multiple continuum fit steps it selects the one with the smallest Chi2 value..
        /// </summary>
        public static string SelectBestFitDescription {
            get {
                return ResourceManager.GetString("SelectBestFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select best fit.
        /// </summary>
        public static string SelectBestFitTitle {
            get {
                return ResourceManager.GetString("SelectBestFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WavelengthConversionDescription {
            get {
                return ResourceManager.GetString("WavelengthConversionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelength conversion.
        /// </summary>
        public static string WavelengthConversionTitle {
            get {
                return ResourceManager.GetString("WavelengthConversionTitle", resourceCulture);
            }
        }
    }
}
