//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SpecSvc.Web.Controls {
    
    
    public partial class Menu {
        
        /// <summary>
        /// Home control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Controls.ToolbarButton Home;
        
        /// <summary>
        /// Search control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Controls.ToolbarButton Search;
        
        /// <summary>
        /// Jobs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Controls.ToolbarButton Jobs;
        
        /// <summary>
        /// MySpectrum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Controls.ToolbarButton MySpectrum;
        
        /// <summary>
        /// Collections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Controls.ToolbarButton Collections;
        
        /// <summary>
        /// Programming control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Controls.ToolbarButton Programming;
        
        /// <summary>
        /// Docs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.Controls.ToolbarButton Docs;
    }
}
