//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SpecSvc.Pipeline.Formats {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormatDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.SpecSvc.Pipeline.Formats.FormatDescriptions", typeof(FormatDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContinuumFitDescription {
            get {
                return ResourceManager.GetString("ContinuumFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuum fit parameters in ASCII.
        /// </summary>
        internal static string ContinuumFitTitle {
            get {
                return ResourceManager.GetString("ContinuumFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LineFitDescription {
            get {
                return ResourceManager.GetString("LineFitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line fit parameters in ASCII.
        /// </summary>
        internal static string LineFitTitle {
            get {
                return ResourceManager.GetString("LineFitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MagnitudeDescription {
            get {
                return ResourceManager.GetString("MagnitudeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnitudes in ASCII.
        /// </summary>
        internal static string MagnitudeTitle {
            get {
                return ResourceManager.GetString("MagnitudeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpectrumAsciiDescription {
            get {
                return ResourceManager.GetString("SpectrumAsciiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum in ASCII.
        /// </summary>
        internal static string SpectrumAsciiTitle {
            get {
                return ResourceManager.GetString("SpectrumAsciiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpectrumPlotDescription {
            get {
                return ResourceManager.GetString("SpectrumPlotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum plot.
        /// </summary>
        internal static string SpectrumPlotTitle {
            get {
                return ResourceManager.GetString("SpectrumPlotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpectrumVoTableDescription {
            get {
                return ResourceManager.GetString("SpectrumVoTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum in VOTable.
        /// </summary>
        internal static string SpectrumVoTableTitle {
            get {
                return ResourceManager.GetString("SpectrumVoTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SpectrumXmlDescription {
            get {
                return ResourceManager.GetString("SpectrumXmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum in XML.
        /// </summary>
        internal static string SpectrumXmlTitle {
            get {
                return ResourceManager.GetString("SpectrumXmlTitle", resourceCulture);
            }
        }
    }
}
